name: Deploy to Nomad

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

env:
  NOMAD_VERSION: 1.9.7
  NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
  NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download workflow run output
        uses: actions/download-artifact@v4
        with:
          name: deploy-data
          path: ./tmp

      - name: Set image tag from artifact
        id: read_tag
        run: |
          TAG=$(cat ./tmp/short_sha.txt)
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Setup Nomad CLI
        uses: hashicorp/setup-nomad@v1
        with:
          version: ${{ env.NOMAD_VERSION }}

      - name: Generate Nomad file from template
        run: |
          export IMAGE_TAG=${{ github.event.inputs.tag }}
          export DEPLOY_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          envsubst < template.nomad.hcl > job.nomad.hcl

      - name: Run Nomad job
        run: nomad run job.nomad.hcl
